import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Построй сайт - Generated Site",
  description: "Site generated by Построй сайт AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>{children}</body>
    </html>
  );
}
